---
- name: Conectar ao Servidor 37 (NGINX)
  hosts: balanceador
  user: root
  become: true

  tasks:
    
    - name: Instalar EPEL
      yum: name=epel-release.noarch state=latest

    - name: ATUALIZAR O YUM
      yum: name=* state=latest

    - name: Instalar NGINX
      yum: name=nginx.x86_64 state=latest

    - name: Instalar GIT
      yum: name=git.x86_64 state=latest

    - name: Criar repositório
      shell: mkdir /root/balanceador

    - git:
        repo: 'https://github.com/paulomiyasaka/ansible.git'
        dest: /root/balanceador
        clone: yes

    - name: Copiar app.conf APP - NGINX
      copy: src=~/balanceador/nginx/app.conf dest=/etc/nginx/conf.d/ backup=yes
    
    - name: Copiar nginx.conf NGINX_CONF - NGINX
      copy: src=~/balanceador/nginx/nginx.conf dest=/etc/nginx/ backup=yes

    - name: Ativando e habilitando NGINX
      service: name=nginx state=started enabled=yes


    #- name: Copiar nginx.conf CONF - NGINX
    #  copy: src=~/Ansible/nginx_conf/nginx.conf dest=/etc/nginx/ backup=yes

- include: aplicacao.yml
#- include: aplicacao2.yml
- include: banco_dados.yml
